manifest_version = "0.0.1"

[meta]
id = "mistral-7b"
name = "Mistral 7B"
description = "The 7B model released by Mistral AI"
tag = "instruct-Q4_K_M"
license = "Apache-2.0"
repository = "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2"

[download]
file_url = "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF/resolve/main/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
hash = "3e0039fd0273fcbebb49228943b17831aadd55cbcbf56f0af00499be2040ccf9"
file_name = "mistral-7b-instruct-v0.2.Q4_K_M.gguf"